#!/bin/bash
#
# Synopsis: with-xmpp-bridge COMMAND [ARG]...
#
# Runs a command with its stdin and stdout connected to xmpp-bridge,
# as a sort of bidirectional pipe.
#
# Parameters to xmpp-bridge must be passed in the environment, see
# man:xmpp-bridge(1) for details.

set -euo pipefail
pipexec -- [ A "$@" ] [ B /usr/bin/xmpp-bridge ] "{A:1>B:0}" "{B:1>A:0}"
